'use client';
import { useEffect,useState } from 'react';
const api=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000';
type Table={id:string;name:string;_count:{rows:number};columns:{name:string;kind:string}[]};
export default function Home(){const [email,setEmail]=useState('demo@gtmai.dev');const [password,setPassword]=useState('demo1234');const [token,setToken]=useState('');const [tables,setTables]=useState<Table[]>([]);const [workspace,setWorkspace]=useState('');const [error,setError]=useState('');
async function login(){const response=await fetch(`${api}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json() as {token?:string;workspaceId?:string;error?:string};if(!response.ok){setError(data.error??'Login failed');return}localStorage.setItem('token',data.token??'');setToken(data.token??'');setWorkspace(data.workspaceId??'')}
useEffect(()=>{if(!token||!workspace)return;fetch(`${api}/workspaces/${workspace}/tables`,{headers:{authorization:`Bearer ${token}`}}).then((r)=>r.json()).then((data:Table[])=>setTables(data))},[token,workspace]);
if(!token)return <main className="min-h-screen grid place-items-center"><form className="w-96 rounded-xl bg-white p-8 shadow" onSubmit={(e)=>{e.preventDefault();void login()}}><h1 className="mb-6 text-2xl font-bold">GTM AI</h1><input className="mb-3 w-full rounded border p-2" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Email"/><input className="mb-3 w-full rounded border p-2" type="password" value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="Password"/><button className="w-full rounded bg-indigo-600 p-2 text-white">Log in</button>{error&&<p className="text-red-600">{error}</p>}</form></main>;
return <main className="flex min-h-screen"><aside className="w-60 border-r bg-white p-5"><h1 className="mb-8 text-xl font-bold">GTM AI</h1><nav className="space-y-3 text-sm"><div>Tables</div><div>Connections</div><div>Credits</div></nav></aside><section className="flex-1 p-8"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-semibold">Your tables</h2><button className="rounded bg-indigo-600 px-4 py-2 text-white" onClick={()=>void fetch(`${api}/workspaces/${workspace}/tables`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({name:'New table'})}).then(()=>location.reload())}>+ New table</button></div><div className="grid gap-4 md:grid-cols-3">{tables.map((table)=><a className="rounded-xl border bg-white p-5 shadow-sm" href={`/tables/${table.id}`} key={table.id}><h3 className="font-semibold">{table.name}</h3><p className="mt-2 text-sm text-slate-500">{table._count.rows} rows · {table.columns.length} columns</p></a>)}</div></section></main>}
