import { z } from 'zod';
import type { Provider, RunContext } from './types';
function provider(id:string,name:string,actions:{id:string;name:string;category:'work_email'|'personal_email'|'phone'|'person'|'company'|'verify'|'search'|'ai'|'other';path:string}[]):Provider {
  const input=z.record(z.unknown()), output=z.record(z.unknown());
  return {id,name,auth:{type:'apiKey',fields:[{key:'apiKey',label:'API key',secret:true}]},actions:actions.map((action)=>({id:action.id,name:action.name,category:action.category,input,output,creditCost:2,run:async (data:Record<string,unknown>,ctx:RunContext)=>{const url=`https://api.${id}.com/${action.path}`;const response=await ctx.fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${ctx.credentials.apiKey??''}`},body:JSON.stringify(data)});if(!response.ok)return {found:false,reason:`${response.status}`};return {found:true,data:await response.json()}}})) as unknown as Provider['actions']};
}
export const hunterProvider=provider('hunter','Hunter',[{id:'hunter.findEmail',name:'Email finder',category:'work_email',path:'v2/email-finder'},{id:'hunter.verifyEmail',name:'Email verifier',category:'verify',path:'v2/email-verifier'},{id:'hunter.domainSearch',name:'Domain search',category:'search',path:'v2/domain-search'},{id:'hunter.enrichCompany',name:'Company enrichment',category:'company',path:'v2/companies/find'}]);
export const prospeoProvider=provider('prospeo','Prospeo',[{id:'prospeo.findEmail',name:'Email finder',category:'work_email',path:'email-finder'},{id:'prospeo.findMobile',name:'Mobile finder',category:'phone',path:'mobile-finder'},{id:'prospeo.enrichCompany',name:'Company enrichment',category:'company',path:'company-enrich'}]);
export const datagmaProvider=provider('datagma','Datagma',[{id:'datagma.enrich',name:'Full enrichment',category:'person',path:'enrich'}]);
export const apolloProvider=provider('apollo','Apollo',[{id:'apollo.peopleMatch',name:'People match',category:'person',path:'v1/people/match'},{id:'apollo.orgEnrich',name:'Organization enrich',category:'company',path:'v1/organizations/enrich'}]);
export const pdlProvider=provider('peopledatalabs','People Data Labs',[{id:'peopledatalabs.personEnrich',name:'Person enrich',category:'person',path:'v5/person/enrich'},{id:'peopledatalabs.companyEnrich',name:'Company enrich',category:'company',path:'v5/company/enrich'}]);
